name: Docker CI (GitHub)

on:
  push:
    branches:
      - 'master'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: no767/rin-deviantart-token-refresher:latest
          build_args: PM2_PUBLIC_KEY_INGEST=${{ secrets.PM2_PUBLIC_KEY_INGEST }}, PM2_SECRET_KEY_INGEST=${{ secrets.PM2_SECRET_KEY_INGEST }}